import './js/refs';
import './js/render-movies';
import './js/footerModal';
import './js/team-data';
import './js/render-team-card';
import './js/spinner';
import './js/film-modal';
import './js/trailer-modal';
import './js/get-genres';
